# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/moto/shamu/setup-makefiles.sh

$(call inherit-product, vendor/moto/shamu/shamu-vendor-blobs.mk)

#fmas n6 specific
PRODUCT_PROPERTY_OVERRIDES += \
	PRODUCT_NAME=Shamu \
    BUILD_FINGERPRINT=google/shamu/shamu:5.1.1/LMY48G/1914015:user/release-keys \
    PRIVATE_BUILD_DESC="shamu-user 5.1.1 LMY48G 1914015 release-keys" \
	keyguard.no_require_sim=true \
    ro.url.legal=http://www.google.com/intl/%s/mobile/android/basic/phone-legal.html \
    ro.url.legal.android_privacy=http://www.google.com/intl/%s/mobile/android/basic/privacy.html \
    ro.com.google.clientidbase=android-google \
    ro.com.android.wifi-watchlist=GoogleGuest \
    ro.setupwizard.enterprise_mode=1 \
    ro.com.android.dateformat=MM-dd-yyyy \
    ro.com.android.dataroaming=false \
    drm.service.enabled=true \
    net.tethering.noprovisioning=true \
    persist.sys.dun.override=0 \
    ro.build.selinux=1 \
    ro.adb.secure=1 \
    ro.config.vc_music_vol_steps=30 \
    fmas.spkr_6ch=35,20,110 \
    fmas.spkr_2ch=35,25 \
    fmas.spkr_angles=10 \
    fmas.spkr_sgain=0 \
    media.aac_51_output_enabled=true \
    persist.rcs.supported=0 \
    persist.radio.sib16_support=1 \
    drm.service.enabled=true \
    persist.audio.dualmic.config=endfire \
    persist.audio.fluence.voicecall=true \
    persist.audio.fluence.voicerec=false \
    persist.audio.fluence.speaker=false 

# Prebuilt APKs
PRODUCT_PACKAGES += \
    atfwd \
    ims \
    RCSBootstraputil \
    RcsImsBootstraputil \
    RcsService \
    TimeService \
    VZWAPNLib

# Prebuilt jars
PRODUCT_PACKAGES += \
    com.motorola.ims.rcsmanager \
    com.verizon.hardware.telephony.ehrpd \
    com.verizon.hardware.telephony.lte \
    com.verizon.ims \
    org.simalliance.openmobileapi \
    rcsimssettings \
    rcsservice

# Prebuilt privileged APKs
PRODUCT_PACKAGES += \
    appdirectedsmspermission \
    AppDirectedSMSProxy \
    BuaContactAdapter \
    CNEService \
    MotoSignatureApp \
    TriggerEnroll \
    TriggerTrainingService \
    VZWAPNService

# Prebuilt vendor/libs needed for compilation
PRODUCT_PACKAGES += \
    libtime_genoff
